#!/usr/bin/env bash

make -s copy-cs-config

# Grab the staged files
stagedFiles=($(git diff --cached --name-only --diff-filter=AM))
files="${stagedFiles[@]}"
if [ "$files" = '' ]
then
  exit 0
fi

# Construct the phpcs command.
command=$(echo "make -s twig-fix files=\"${files}\"")
echo "$command"

# Run the command on our docker container and capture the results
make -s twig-fix files="${files}" >> results_twig.txt

results=$(cat results_twig.txt)
$(rm results_twig.txt)

# Block the commit from going through if needed
foundErrors=$(grep -o "begin diff" <<< ${results})
returnCode=0

if [ "$foundErrors" != '' ]
then
    echo "${results}" >&2

    echo "You had some twig errors, don't forget to add these fixes to git before committing again!" >&2

    # Exit so you can stage the files and commit again
    returnCode=1
fi
exit $returnCode
