#!/usr/bin/env bash

# Grab the staged files
stagedFiles=($(git diff --cached --name-only --diff-filter=AM | grep -e .php$))
files="${stagedFiles[@]}"
if [ "$files" = '' ]
then
  exit 0
fi

# Run fixer and add changes to the commit
make -s phpcs-fix files="${files}"
git add ${files}