#!/usr/bin/env bash

if [ "${CF_COMMIT_PHPSTAN_ENABLED:-1}" != 1 ]
then
  echo "pre-commit phpstan disabled"
  exit 0
fi

# Grab the staged files
stagedFiles=($(git diff --cached --name-only --diff-filter=AM src | grep -e .php$))
files="${stagedFiles[@]}"
if [ "$files" = '' ]
then
  echo "phpstan: no php files to check"
  exit 0
fi

make -s det cmd="vendor/bin/phpstan analyse --memory-limit=-1 --no-interaction ${files}"
