#!/usr/bin/env sh

make -s copy-phpcs-config

# Application directory
applicationDirectory='.'

# Grab the staged files
stagedFiles=($(git diff --cached --name-only --diff-filter=AM))
files="${stagedFiles[@]}"

# Construct the phpcs command.
command=$(echo "make -s lint-phpcs files=\"${files}\"")
echo "$command"

# Run the command on our docker container and capture the results
make -s lint-phpcs files="${files}" >> results.txt

results=$(cat results.txt)
$(rm results.txt)

# Block the commit from going through if needed
foundErrors=$(grep -o "begin diff" <<< ${results})
returnCode=0

if [ "$foundErrors" != '' ]
then
    echo "${results}" >&2

    command=$(echo "make -s lint-phpcs-fix options=\"--quiet\" files=\"${files}\"")
    echo "$command"
    
    make -s lint-phpcs-fix options="--quiet" files="${files}"
     
    echo "You had some phpcs errors, don't forget to add these fixes to git before commiting again!" >&2

    # Exit so you can stage the files and commit again
    returnCode=1
fi
exit $returnCode
