#!/usr/bin/env bash

if [ "${CF_COMMIT_PSALM_ENABLED:-1}" != 1 ]
then
  echo "pre-commit psalm disabled"
  exit 0
fi

# Grab the staged files
stagedFiles=($(git diff --cached --name-only --diff-filter=AM src | grep -e .php$))
files="${stagedFiles[@]}"
if [ "$files" = '' ]
then
  echo "psalm: no php files to check"
  exit 0
fi

make -s det cmd="vendor/bin/psalm --no-progress --no-cache ${files}"